### ISSUE TITLE
sharing your Analog Sound Analyzer 

### ISSUE THREAD

**Issue by aeonSolutions** [donnersm/Analog-Analyzer#2]
Hi Mark Donners,
just to let you know, i've added a link to this project of yours to my project "Home Safety & Health". Here's the link for you to see:
[https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home%20Automation%20Safety%20&%20Health/readme.md#projects-from-other-diy-makers](https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home%20Automation%20Safety%20&%20Health/readme.md#projects-from-other-diy-makers)

keep up the good work.
thank you

**Comment by donnersm** [comment]
Thanks RegardsMarkVerstuurd vanaf mijn iPhoneOp 3 okt. 2023 om 10:52 heeft Miguel Tomas Silva ***@***.***> het volgende geschreven:﻿
Hi Mark Donners,
just to let you know, i've added a link to this project of yours to my project "Home Safety & Health". Here's the link for you to see:
https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home%20Automation%20Safety%20&%20Health/readme.md#projects-from-other-diy-makers
keep up the good work.
thank you
